name: Update Multi Seasons

on:
  workflow_dispatch:   # <-- manuell im GitHub UI starten

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run multi-season update
        run: node update-multi.js

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add games-*.json
          git commit -m "Auto-update alle Saisons ($(date))" || echo "Keine Änderungen"
          git pull --rebase origin main || true
          git push
